name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ '*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Restore dependencies
        run: dotnet restore Skippy.sln 

      - name: Build
        run: dotnet build $Env:GITHUB_WORKSPACE\Skippy.sln /p:Configuration=Release /p:DefineConstants=XL_NOAUTOUPDATE

      - name: Create Package Directory
        run: mkdir -Path .\Skippy\bin\Package\ -ErrorAction:Continue

      - name: Package
        uses: vimtor/action-zip@v1
        with:
          files: Skippy\bin\x64\Release\Skippy.dll Skippy\bin\x64\Release\Skippy.json Skippy\bin\x64\Release\Skippy.pdb
          dest: Skippy\bin\Package\Skippy.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') 
        with:
          files: Skippy\bin\Package\Skippy.zip
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
